#!/bin/bash
if [[ -z $(which docker) ]]; then
    echo " ** Install Docker first, then re-run this script. Quitting ** "
    exit 1
fi
    
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
sudo chmod +x /usr/local/bin/docker-compose 
sudo docker-compose --version 

